GEMINI_API_KEY = "GEMINI_API_KEY_AQ_FORMAT_EXPERIMENTAL"
TELEGRAM_BOT_TOKEN = "TELEGRAM_BOT_TOKEN_EXPERIMENTAL"
TELEGRAM_CHAT_ID = "TELEGRAM_CHAT_ID_EXPERIMENTAL"
SECRET_TOKEN = "test_token_123"

settings = None  # Disabled os.getenv() dependencies for hardcoded experimental testing